name: jailbase
description: A wrapper for the jailbase API
version: 0.0.2
homepage: https://github.com/gquarles/jailbase

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.1.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

